// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: saacs/biochain/v0/state.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SpecimenHistory with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SpecimenHistory) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecimenHistory with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SpecimenHistoryMultiError, or nil if none found.
func (m *SpecimenHistory) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecimenHistory) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEntries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SpecimenHistoryValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SpecimenHistoryValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SpecimenHistoryValidationError{
					field:  fmt.Sprintf("Entries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetHiddenTxs()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenHistoryValidationError{
					field:  "HiddenTxs",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenHistoryValidationError{
					field:  "HiddenTxs",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHiddenTxs()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenHistoryValidationError{
				field:  "HiddenTxs",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SpecimenHistoryMultiError(errors)
	}

	return nil
}

// SpecimenHistoryMultiError is an error wrapping multiple validation errors
// returned by SpecimenHistory.ValidateAll() if the designated constraints
// aren't met.
type SpecimenHistoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecimenHistoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecimenHistoryMultiError) AllErrors() []error { return m }

// SpecimenHistoryValidationError is the validation error returned by
// SpecimenHistory.Validate if the designated constraints aren't met.
type SpecimenHistoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecimenHistoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecimenHistoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecimenHistoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecimenHistoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecimenHistoryValidationError) ErrorName() string { return "SpecimenHistoryValidationError" }

// Error satisfies the builtin error interface
func (e SpecimenHistoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimenHistory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecimenHistoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecimenHistoryValidationError{}

// Validate checks the field values on SpecimenHistoryEntry with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SpecimenHistoryEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecimenHistoryEntry with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SpecimenHistoryEntryMultiError, or nil if none found.
func (m *SpecimenHistoryEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecimenHistoryEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxId

	// no validation rules for IsDelete

	// no validation rules for IsHidden

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenHistoryEntryValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenHistoryEntryValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenHistoryEntryValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Note

	if all {
		switch v := interface{}(m.GetValue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenHistoryEntryValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenHistoryEntryValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenHistoryEntryValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SpecimenHistoryEntryMultiError(errors)
	}

	return nil
}

// SpecimenHistoryEntryMultiError is an error wrapping multiple validation
// errors returned by SpecimenHistoryEntry.ValidateAll() if the designated
// constraints aren't met.
type SpecimenHistoryEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecimenHistoryEntryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecimenHistoryEntryMultiError) AllErrors() []error { return m }

// SpecimenHistoryEntryValidationError is the validation error returned by
// SpecimenHistoryEntry.Validate if the designated constraints aren't met.
type SpecimenHistoryEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecimenHistoryEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecimenHistoryEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecimenHistoryEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecimenHistoryEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecimenHistoryEntryValidationError) ErrorName() string {
	return "SpecimenHistoryEntryValidationError"
}

// Error satisfies the builtin error interface
func (e SpecimenHistoryEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimenHistoryEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecimenHistoryEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecimenHistoryEntryValidationError{}

// Validate checks the field values on SpecimenUpdate with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SpecimenUpdate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecimenUpdate with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SpecimenUpdateMultiError,
// or nil if none found.
func (m *SpecimenUpdate) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecimenUpdate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSpecimen()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenUpdateValidationError{
					field:  "Specimen",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenUpdateValidationError{
					field:  "Specimen",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpecimen()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenUpdateValidationError{
				field:  "Specimen",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMask()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenUpdateValidationError{
					field:  "Mask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenUpdateValidationError{
					field:  "Mask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenUpdateValidationError{
				field:  "Mask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SpecimenUpdateMultiError(errors)
	}

	return nil
}

// SpecimenUpdateMultiError is an error wrapping multiple validation errors
// returned by SpecimenUpdate.ValidateAll() if the designated constraints
// aren't met.
type SpecimenUpdateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecimenUpdateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecimenUpdateMultiError) AllErrors() []error { return m }

// SpecimenUpdateValidationError is the validation error returned by
// SpecimenUpdate.Validate if the designated constraints aren't met.
type SpecimenUpdateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecimenUpdateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecimenUpdateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecimenUpdateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecimenUpdateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecimenUpdateValidationError) ErrorName() string { return "SpecimenUpdateValidationError" }

// Error satisfies the builtin error interface
func (e SpecimenUpdateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimenUpdate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecimenUpdateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecimenUpdateValidationError{}

// Validate checks the field values on Date with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Date) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Date with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DateMultiError, or nil if none found.
func (m *Date) ValidateAll() error {
	return m.validate(true)
}

func (m *Date) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Verbatim

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DateValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DateValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DateValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Year

	// no validation rules for Month

	// no validation rules for Day

	if len(errors) > 0 {
		return DateMultiError(errors)
	}

	return nil
}

// DateMultiError is an error wrapping multiple validation errors returned by
// Date.ValidateAll() if the designated constraints aren't met.
type DateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DateMultiError) AllErrors() []error { return m }

// DateValidationError is the validation error returned by Date.Validate if the
// designated constraints aren't met.
type DateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DateValidationError) ErrorName() string { return "DateValidationError" }

// Error satisfies the builtin error interface
func (e DateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DateValidationError{}

// Validate checks the field values on Researcher with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Researcher) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Researcher with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResearcherMultiError, or
// nil if none found.
func (m *Researcher) ValidateAll() error {
	return m.validate(true)
}

func (m *Researcher) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FirstName

	// no validation rules for LastName

	// no validation rules for MiddleName

	if len(errors) > 0 {
		return ResearcherMultiError(errors)
	}

	return nil
}

// ResearcherMultiError is an error wrapping multiple validation errors
// returned by Researcher.ValidateAll() if the designated constraints aren't met.
type ResearcherMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResearcherMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResearcherMultiError) AllErrors() []error { return m }

// ResearcherValidationError is the validation error returned by
// Researcher.Validate if the designated constraints aren't met.
type ResearcherValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResearcherValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResearcherValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResearcherValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResearcherValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResearcherValidationError) ErrorName() string { return "ResearcherValidationError" }

// Error satisfies the builtin error interface
func (e ResearcherValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResearcher.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResearcherValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResearcherValidationError{}

// Validate checks the field values on Specimen with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Specimen) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SpecimenMultiError, or nil
// if none found.
func (m *Specimen) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionId

	// no validation rules for SpecimenId

	if all {
		switch v := interface{}(m.GetPrimary()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Primary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Primary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPrimary()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenValidationError{
				field:  "Primary",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSecondary()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Secondary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Secondary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSecondary()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenValidationError{
				field:  "Secondary",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTaxon()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Taxon",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Taxon",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTaxon()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenValidationError{
				field:  "Taxon",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetGeoreference()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Georeference",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "Georeference",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGeoreference()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenValidationError{
				field:  "Georeference",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	{
		sorted_keys := make([]string, len(m.GetImages()))
		i := 0
		for key := range m.GetImages() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetImages()[key]
			_ = val

			// no validation rules for Images[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, SpecimenValidationError{
							field:  fmt.Sprintf("Images[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, SpecimenValidationError{
							field:  fmt.Sprintf("Images[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return SpecimenValidationError{
						field:  fmt.Sprintf("Images[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	{
		sorted_keys := make([]string, len(m.GetLoans()))
		i := 0
		for key := range m.GetLoans() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetLoans()[key]
			_ = val

			// no validation rules for Loans[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, SpecimenValidationError{
							field:  fmt.Sprintf("Loans[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, SpecimenValidationError{
							field:  fmt.Sprintf("Loans[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return SpecimenValidationError{
						field:  fmt.Sprintf("Loans[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	{
		sorted_keys := make([]string, len(m.GetGrants()))
		i := 0
		for key := range m.GetGrants() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetGrants()[key]
			_ = val

			// no validation rules for Grants[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, SpecimenValidationError{
							field:  fmt.Sprintf("Grants[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, SpecimenValidationError{
							field:  fmt.Sprintf("Grants[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return SpecimenValidationError{
						field:  fmt.Sprintf("Grants[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpecimenValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpecimenValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SpecimenMultiError(errors)
	}

	return nil
}

// SpecimenMultiError is an error wrapping multiple validation errors returned
// by Specimen.ValidateAll() if the designated constraints aren't met.
type SpecimenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecimenMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecimenMultiError) AllErrors() []error { return m }

// SpecimenValidationError is the validation error returned by
// Specimen.Validate if the designated constraints aren't met.
type SpecimenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecimenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecimenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecimenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecimenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecimenValidationError) ErrorName() string { return "SpecimenValidationError" }

// Error satisfies the builtin error interface
func (e SpecimenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecimenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecimenValidationError{}

// Validate checks the field values on SpecimenList with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SpecimenList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecimenList with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SpecimenListMultiError, or
// nil if none found.
func (m *SpecimenList) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecimenList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSpecimens() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SpecimenListValidationError{
						field:  fmt.Sprintf("Specimens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SpecimenListValidationError{
						field:  fmt.Sprintf("Specimens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SpecimenListValidationError{
					field:  fmt.Sprintf("Specimens[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SpecimenListMultiError(errors)
	}

	return nil
}

// SpecimenListMultiError is an error wrapping multiple validation errors
// returned by SpecimenList.ValidateAll() if the designated constraints aren't met.
type SpecimenListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecimenListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecimenListMultiError) AllErrors() []error { return m }

// SpecimenListValidationError is the validation error returned by
// SpecimenList.Validate if the designated constraints aren't met.
type SpecimenListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecimenListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecimenListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecimenListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecimenListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecimenListValidationError) ErrorName() string { return "SpecimenListValidationError" }

// Error satisfies the builtin error interface
func (e SpecimenListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimenList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecimenListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecimenListValidationError{}

// Validate checks the field values on SpecimenMap with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SpecimenMap) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecimenMap with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SpecimenMapMultiError, or
// nil if none found.
func (m *SpecimenMap) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecimenMap) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetSpecimens()))
		i := 0
		for key := range m.GetSpecimens() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetSpecimens()[key]
			_ = val

			// no validation rules for Specimens[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, SpecimenMapValidationError{
							field:  fmt.Sprintf("Specimens[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, SpecimenMapValidationError{
							field:  fmt.Sprintf("Specimens[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return SpecimenMapValidationError{
						field:  fmt.Sprintf("Specimens[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	// no validation rules for Bookmark

	if len(errors) > 0 {
		return SpecimenMapMultiError(errors)
	}

	return nil
}

// SpecimenMapMultiError is an error wrapping multiple validation errors
// returned by SpecimenMap.ValidateAll() if the designated constraints aren't met.
type SpecimenMapMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecimenMapMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecimenMapMultiError) AllErrors() []error { return m }

// SpecimenMapValidationError is the validation error returned by
// SpecimenMap.Validate if the designated constraints aren't met.
type SpecimenMapValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecimenMapValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecimenMapValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecimenMapValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecimenMapValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecimenMapValidationError) ErrorName() string { return "SpecimenMapValidationError" }

// Error satisfies the builtin error interface
func (e SpecimenMapValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimenMap.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecimenMapValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecimenMapValidationError{}

// Validate checks the field values on Specimen_Primary with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Specimen_Primary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Primary with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Specimen_PrimaryMultiError, or nil if none found.
func (m *Specimen_Primary) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Primary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CatalogNumber

	// no validation rules for AccessionNumber

	// no validation rules for FieldNumber

	// no validation rules for TissueNumber

	// no validation rules for Cataloger

	// no validation rules for Collector

	// no validation rules for Determiner

	if all {
		switch v := interface{}(m.GetFieldDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "FieldDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "FieldDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFieldDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_PrimaryValidationError{
				field:  "FieldDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCatalogDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "CatalogDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "CatalogDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCatalogDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_PrimaryValidationError{
				field:  "CatalogDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDeterminedDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "DeterminedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "DeterminedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeterminedDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_PrimaryValidationError{
				field:  "DeterminedDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DeterminedReason

	if all {
		switch v := interface{}(m.GetOriginalDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "OriginalDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "OriginalDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOriginalDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_PrimaryValidationError{
				field:  "OriginalDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_PrimaryValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_PrimaryValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Specimen_PrimaryMultiError(errors)
	}

	return nil
}

// Specimen_PrimaryMultiError is an error wrapping multiple validation errors
// returned by Specimen_Primary.ValidateAll() if the designated constraints
// aren't met.
type Specimen_PrimaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_PrimaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_PrimaryMultiError) AllErrors() []error { return m }

// Specimen_PrimaryValidationError is the validation error returned by
// Specimen_Primary.Validate if the designated constraints aren't met.
type Specimen_PrimaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_PrimaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_PrimaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_PrimaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_PrimaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_PrimaryValidationError) ErrorName() string { return "Specimen_PrimaryValidationError" }

// Error satisfies the builtin error interface
func (e Specimen_PrimaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Primary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_PrimaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_PrimaryValidationError{}

// Validate checks the field values on Specimen_Secondary with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Specimen_Secondary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Secondary with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Specimen_SecondaryMultiError, or nil if none found.
func (m *Specimen_Secondary) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Secondary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sex

	// no validation rules for Age

	// no validation rules for Weight

	// no validation rules for WeightUnits

	{
		sorted_keys := make([]string, len(m.GetPreparations()))
		i := 0
		for key := range m.GetPreparations() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetPreparations()[key]
			_ = val

			// no validation rules for Preparations[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, Specimen_SecondaryValidationError{
							field:  fmt.Sprintf("Preparations[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, Specimen_SecondaryValidationError{
							field:  fmt.Sprintf("Preparations[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return Specimen_SecondaryValidationError{
						field:  fmt.Sprintf("Preparations[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	// no validation rules for Condition

	// no validation rules for Molt

	// no validation rules for Notes

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_SecondaryValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_SecondaryValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_SecondaryValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Specimen_SecondaryMultiError(errors)
	}

	return nil
}

// Specimen_SecondaryMultiError is an error wrapping multiple validation errors
// returned by Specimen_Secondary.ValidateAll() if the designated constraints
// aren't met.
type Specimen_SecondaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_SecondaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_SecondaryMultiError) AllErrors() []error { return m }

// Specimen_SecondaryValidationError is the validation error returned by
// Specimen_Secondary.Validate if the designated constraints aren't met.
type Specimen_SecondaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_SecondaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_SecondaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_SecondaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_SecondaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_SecondaryValidationError) ErrorName() string {
	return "Specimen_SecondaryValidationError"
}

// Error satisfies the builtin error interface
func (e Specimen_SecondaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Secondary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_SecondaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_SecondaryValidationError{}

// Validate checks the field values on Specimen_Taxon with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Specimen_Taxon) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Taxon with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Specimen_TaxonMultiError,
// or nil if none found.
func (m *Specimen_Taxon) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Taxon) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Kingdom

	// no validation rules for Phylum

	// no validation rules for Class

	// no validation rules for Order

	// no validation rules for Family

	// no validation rules for Genus

	// no validation rules for Species

	// no validation rules for Subspecies

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_TaxonValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_TaxonValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_TaxonValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Specimen_TaxonMultiError(errors)
	}

	return nil
}

// Specimen_TaxonMultiError is an error wrapping multiple validation errors
// returned by Specimen_Taxon.ValidateAll() if the designated constraints
// aren't met.
type Specimen_TaxonMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_TaxonMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_TaxonMultiError) AllErrors() []error { return m }

// Specimen_TaxonValidationError is the validation error returned by
// Specimen_Taxon.Validate if the designated constraints aren't met.
type Specimen_TaxonValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_TaxonValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_TaxonValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_TaxonValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_TaxonValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_TaxonValidationError) ErrorName() string { return "Specimen_TaxonValidationError" }

// Error satisfies the builtin error interface
func (e Specimen_TaxonValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Taxon.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_TaxonValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_TaxonValidationError{}

// Validate checks the field values on Specimen_Georeference with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Specimen_Georeference) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Georeference with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Specimen_GeoreferenceMultiError, or nil if none found.
func (m *Specimen_Georeference) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Georeference) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Country

	// no validation rules for StateProvince

	// no validation rules for County

	// no validation rules for Locality

	// no validation rules for Latitude

	// no validation rules for Longitude

	// no validation rules for Habitat

	// no validation rules for Continent

	// no validation rules for LocationRemarks

	// no validation rules for CoordinateUncertaintyInMeters

	// no validation rules for GeoreferenceBy

	if all {
		switch v := interface{}(m.GetGeoreferenceDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_GeoreferenceValidationError{
					field:  "GeoreferenceDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_GeoreferenceValidationError{
					field:  "GeoreferenceDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGeoreferenceDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_GeoreferenceValidationError{
				field:  "GeoreferenceDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for GeoreferenceProtocol

	// no validation rules for GeodeticDatum

	// no validation rules for FootprintWkt

	// no validation rules for Notes

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_GeoreferenceValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_GeoreferenceValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_GeoreferenceValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Specimen_GeoreferenceMultiError(errors)
	}

	return nil
}

// Specimen_GeoreferenceMultiError is an error wrapping multiple validation
// errors returned by Specimen_Georeference.ValidateAll() if the designated
// constraints aren't met.
type Specimen_GeoreferenceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_GeoreferenceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_GeoreferenceMultiError) AllErrors() []error { return m }

// Specimen_GeoreferenceValidationError is the validation error returned by
// Specimen_Georeference.Validate if the designated constraints aren't met.
type Specimen_GeoreferenceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_GeoreferenceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_GeoreferenceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_GeoreferenceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_GeoreferenceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_GeoreferenceValidationError) ErrorName() string {
	return "Specimen_GeoreferenceValidationError"
}

// Error satisfies the builtin error interface
func (e Specimen_GeoreferenceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Georeference.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_GeoreferenceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_GeoreferenceValidationError{}

// Validate checks the field values on Specimen_Image with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Specimen_Image) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Image with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Specimen_ImageMultiError,
// or nil if none found.
func (m *Specimen_Image) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Image) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Url

	// no validation rules for Notes

	// no validation rules for Hash

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_ImageValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_ImageValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_ImageValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Specimen_ImageMultiError(errors)
	}

	return nil
}

// Specimen_ImageMultiError is an error wrapping multiple validation errors
// returned by Specimen_Image.ValidateAll() if the designated constraints
// aren't met.
type Specimen_ImageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_ImageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_ImageMultiError) AllErrors() []error { return m }

// Specimen_ImageValidationError is the validation error returned by
// Specimen_Image.Validate if the designated constraints aren't met.
type Specimen_ImageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_ImageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_ImageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_ImageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_ImageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_ImageValidationError) ErrorName() string { return "Specimen_ImageValidationError" }

// Error satisfies the builtin error interface
func (e Specimen_ImageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Image.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_ImageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_ImageValidationError{}

// Validate checks the field values on Specimen_Loan with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Specimen_Loan) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Loan with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Specimen_LoanMultiError, or
// nil if none found.
func (m *Specimen_Loan) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Loan) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Description

	// no validation rules for LoanedBy

	// no validation rules for LoanedTo

	if all {
		switch v := interface{}(m.GetLoanedDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_LoanValidationError{
					field:  "LoanedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_LoanValidationError{
					field:  "LoanedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLoanedDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_LoanValidationError{
				field:  "LoanedDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_LoanValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_LoanValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_LoanValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Specimen_LoanMultiError(errors)
	}

	return nil
}

// Specimen_LoanMultiError is an error wrapping multiple validation errors
// returned by Specimen_Loan.ValidateAll() if the designated constraints
// aren't met.
type Specimen_LoanMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_LoanMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_LoanMultiError) AllErrors() []error { return m }

// Specimen_LoanValidationError is the validation error returned by
// Specimen_Loan.Validate if the designated constraints aren't met.
type Specimen_LoanValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_LoanValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_LoanValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_LoanValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_LoanValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_LoanValidationError) ErrorName() string { return "Specimen_LoanValidationError" }

// Error satisfies the builtin error interface
func (e Specimen_LoanValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Loan.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_LoanValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_LoanValidationError{}

// Validate checks the field values on Specimen_Grant with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Specimen_Grant) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Grant with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Specimen_GrantMultiError,
// or nil if none found.
func (m *Specimen_Grant) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Grant) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Description

	// no validation rules for GrantedBy

	// no validation rules for GrantedTo

	if all {
		switch v := interface{}(m.GetGrantedDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_GrantValidationError{
					field:  "GrantedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_GrantValidationError{
					field:  "GrantedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGrantedDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_GrantValidationError{
				field:  "GrantedDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Specimen_GrantValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Specimen_GrantValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Specimen_GrantValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Specimen_GrantMultiError(errors)
	}

	return nil
}

// Specimen_GrantMultiError is an error wrapping multiple validation errors
// returned by Specimen_Grant.ValidateAll() if the designated constraints
// aren't met.
type Specimen_GrantMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_GrantMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_GrantMultiError) AllErrors() []error { return m }

// Specimen_GrantValidationError is the validation error returned by
// Specimen_Grant.Validate if the designated constraints aren't met.
type Specimen_GrantValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_GrantValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_GrantValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_GrantValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_GrantValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_GrantValidationError) ErrorName() string { return "Specimen_GrantValidationError" }

// Error satisfies the builtin error interface
func (e Specimen_GrantValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Grant.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_GrantValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_GrantValidationError{}

// Validate checks the field values on Specimen_Secondary_Preparation with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Specimen_Secondary_Preparation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Specimen_Secondary_Preparation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// Specimen_Secondary_PreparationMultiError, or nil if none found.
func (m *Specimen_Secondary_Preparation) ValidateAll() error {
	return m.validate(true)
}

func (m *Specimen_Secondary_Preparation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Verbatim

	if len(errors) > 0 {
		return Specimen_Secondary_PreparationMultiError(errors)
	}

	return nil
}

// Specimen_Secondary_PreparationMultiError is an error wrapping multiple
// validation errors returned by Specimen_Secondary_Preparation.ValidateAll()
// if the designated constraints aren't met.
type Specimen_Secondary_PreparationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Specimen_Secondary_PreparationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Specimen_Secondary_PreparationMultiError) AllErrors() []error { return m }

// Specimen_Secondary_PreparationValidationError is the validation error
// returned by Specimen_Secondary_Preparation.Validate if the designated
// constraints aren't met.
type Specimen_Secondary_PreparationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Specimen_Secondary_PreparationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Specimen_Secondary_PreparationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Specimen_Secondary_PreparationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Specimen_Secondary_PreparationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Specimen_Secondary_PreparationValidationError) ErrorName() string {
	return "Specimen_Secondary_PreparationValidationError"
}

// Error satisfies the builtin error interface
func (e Specimen_Secondary_PreparationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecimen_Secondary_Preparation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Specimen_Secondary_PreparationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Specimen_Secondary_PreparationValidationError{}
