// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: saacs/auth/v0/identity.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserDirectMembership with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserDirectMembership) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserDirectMembership with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserDirectMembershipMultiError, or nil if none found.
func (m *UserDirectMembership) ValidateAll() error {
	return m.validate(true)
}

func (m *UserDirectMembership) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionId

	// no validation rules for MspId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetPolices()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserDirectMembershipValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserDirectMembershipValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolices()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserDirectMembershipValidationError{
				field:  "Polices",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Note

	if len(errors) > 0 {
		return UserDirectMembershipMultiError(errors)
	}

	return nil
}

// UserDirectMembershipMultiError is an error wrapping multiple validation
// errors returned by UserDirectMembership.ValidateAll() if the designated
// constraints aren't met.
type UserDirectMembershipMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDirectMembershipMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDirectMembershipMultiError) AllErrors() []error { return m }

// UserDirectMembershipValidationError is the validation error returned by
// UserDirectMembership.Validate if the designated constraints aren't met.
type UserDirectMembershipValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDirectMembershipValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDirectMembershipValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDirectMembershipValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDirectMembershipValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDirectMembershipValidationError) ErrorName() string {
	return "UserDirectMembershipValidationError"
}

// Error satisfies the builtin error interface
func (e UserDirectMembershipValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserDirectMembership.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDirectMembershipValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDirectMembershipValidationError{}
